// Bundles every words/*.json file into words-data.js so index.html
// can be opened directly (file://) without a server.
// Run: node build.js
const fs = require('fs');
const path = require('path');

const dir = path.join(__dirname, 'words');
const words = [];

for (const file of fs.readdirSync(dir).filter(f => f.endsWith('.json')).sort()) {
  try {
    const w = JSON.parse(fs.readFileSync(path.join(dir, file), 'utf8'));
    if (!w.word || !w.meaning) throw new Error('missing "word" or "meaning"');
    words.push({
      word: w.word.trim(),
      meaning: w.meaning.trim(),
      trick: (w.trick || '').trim(),
      examples: Array.isArray(w.examples) ? w.examples : [],
    });
  } catch (e) {
    console.error(`Skipping ${file}: ${e.message}`);
  }
}

fs.writeFileSync(
  path.join(__dirname, 'words-data.js'),
  '// AUTO-GENERATED by build.js — do not edit. Edit files in words/ instead.\n' +
    'window.WORDS = ' + JSON.stringify(words, null, 2) + ';\n'
);
console.log(`Bundled ${words.length} words into words-data.js`);
