// How common a word is, from its Zipf score in src/frequency.json
// (generated by scripts/frequency.py from the wordfreq library).
export const RARITIES = [
  { id: 'common', icon: '🟢', label: 'Common', min: 3.5, hint: 'Used a lot in everyday English — learn to use it.' },
  { id: 'medium', icon: '🟡', label: 'Medium', min: 2.5, hint: 'Seen in books and news now and then.' },
  { id: 'rare', icon: '🔴', label: 'Rare', min: -Infinity, hint: 'Mostly in books — recognising it is usually enough.' },
];
export const RARITY_IDS = RARITIES.map(r => r.id);
export const rarityInfo = id => RARITIES.find(r => r.id === id) || null;

// null when the word hasn't been scored yet.
export function rarityOf(freq) {
  if (typeof freq !== 'number') return null;
  return RARITIES.find(r => freq >= r.min).id;
}
